version: "3.1"

networks:
  network:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports: 
      - "8001:80"
    volumes:
      - ./laravel:/var/www/html/
      - ./apache/log:/var/log/apache2/
      - ./apache/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql
    networks:
      - network
  mysql:
    image: mysql:5.7.29
    container_name: laravel_mysql
    restart: unless-stopped
    ports: 
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root@123
      MYSQL_ROOT_PASSWORD: root@123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - network